### ISSUE TITLE
headers and cookies

### ISSUE THREAD

**Issue by devilxsam** [r0ld3x/terabox-downloader-bot#2]
How to Get headers and cookies , make a video on it

**Comment by r0ld3x** [comment]
ok will make

**Comment by r0ld3x** [comment]
**Try to use premium account for better speed**

WEBSITE: [curlconverter](https://curlconverter.com/)


https://github.com/r0ld3x/terabox-downloader-bot/assets/77254818/02a3d20d-3894-483c-9581-a052842b16e3

**Comment by jimmymeitei** [comment]
headers and cookies how to find it

**Comment by Ddjhg** [comment]
Does premium account required for it??

**Comment by r0ld3x** [comment]
> Does premium account required for it??

API IS DEAD

**Comment by Ddjhg** [comment]
Sir Any references to create new api?

**Comment by r0ld3x** [comment]
> Sir Any references to create new api?

Terabox security has been updated. I dont have any ways to fix it for now. 

:)
